name: crud_exemplo_1
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  provider: ^6.0.5
  uuid: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  confirm_dialog: ^1.0.2
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
